language: python
python:
  - 3.7
script:
  - pytest --cov=app --cov-report=xml
install:
  - "pip install --upgrade pip"
  - "pip install pipenv"
  - "pipenv install --dev"
  - "pip install codecov"
after_success:
  - codecov
